### PR TITLE
bash completion for options and repo names

### PR DESCRIPTION
**Pull request by perlpunk**
See also #71

### CODE REVIEW

**Comment by ingydotnet** [comment]
Great patch. Works good for me on bash.

A couple requests:

1) Add 'clone' to commands that complete repos!
2) I think we should limit the repo completion to 50. It will get the last 50
   touched, it will fetch them in one request, so faster and more useful UX.

BTW, where do the results get cached?

**Comment by perlpunk** [comment]
1) clone is now added. the regex to parse usage from git-hub.swim wasn't correct

**Comment by perlpunk** [comment]
re "where do the results get cached?"
thery are cached in a variable `__git_hub_reponames`. this is needed so that typing TAB several times in one command doesn't have to do an API call more than once.

**Comment by perlpunk** [comment]
I'd suggest taking out the limit for now, merge and work on it later.
question is, what should happen, if one types `user/a<TAB>` and there is no repo beginning with 'a' among the most recent 50?
or should only `user/<TAB>` have a limit, but not `user/a<TAB>`?

**Comment by ingydotnet** [comment]
@perlpunk, please rebase this to latest master.

**Comment by perlpunk** [comment]
rebased

**Comment by perlpunk** [comment]
I had some thoughts on this.
For my own github client I am using the search API.
So instead of getting the list of all user repos do a search API request. This will only work if the searched word has at least one character though, so
`username/<TAB>` wouldn't do any completion, but `username/x<TAB>`.

This will be reasonably fast.
If you search for 'x', it will return repos that have 'x' anywhere, but the repos which start with 'x' will be at the beginning of the list, so it would do what we need.
Of course first one would have to implement the necessary search commands.

I could create a pull request which does the option and command completion and leaves out this dynamic stuff for now.

**Comment by perlpunk** [comment]
created #193 (bash completion without the dynamic repo name completion)

**Pull request closed without merging**
