### PR TITLE
add gist commands

### PR DESCRIPTION
**Pull request by perlpunk**
See also #175

### CODE REVIEW

**Comment by frioux** [comment]
This is great!  Just did a `git hub gist --raw | git hub gist-clone =` in a _~/code/gists_ dir and am pleased by all the network and disk io :)

**Comment by frioux** [comment]
Would be nice to be able to `git hub gist-init` to create a new local repo from a (nearly) empty gist

**Comment by perlpunk** [comment]
as discussed on irc, gist-init creates an almost empty gist with a .gitignore file and clones it.
should gist-new also clone the gist after creating?

**Comment by perlpunk** [comment]
rebased branch because of conflict with master

**Comment by ingydotnet** [comment]
@perlpunk, THis is great work. Sorry for sitting on it so long. I'll want to
change things up a bit, but getting it out there for now.

Thanks!!!

**Pull request closed without merging**
