### PR TITLE
Add Changelog

### PR DESCRIPTION
**Pull request by perlpunk**
As a lot of people are already using git-hub it would be useful to have
a Changes file so they don't have to dig through the commit log to
see what's new/changed.
Or at least create a new release tag since the last one is already one year old.

### CODE REVIEW

**Comment by perlpunk** [comment]
I added a Changes file.
Splitted 2015 into 0.1.5.06, 0.1.5.09, 0.1.5.12

**Comment by perlpunk** [comment]
I added a test that checks for a valid Changea file. rebased

**Comment by perlpunk** [comment]
added the recent changes

**Comment by ingydotnet** [comment]
Applied. Pushed. Thanks!

**Pull request closed without merging**
