### PR TITLE
add environment variable/config for force-cache

### PR DESCRIPTION
**Pull request by perlpunk**
this option uses the cached response without checking for changes
on the server.
it's useful for faster tab completion on reponames.

### CODE REVIEW

**Comment by ingydotnet** [comment]
@perlpunk, please rebase this to latest master.

**Comment by perlpunk** [comment]
rebased

**Comment by perlpunk** [comment]
I removed the option --fore-cache and replaced it with get-var force-cache
so that you can use GIT_HUB_FORCE_CACHE

**Comment by perlpunk** [comment]
rebased to current master, squashed commits into a single one.

**Comment by perlpunk** [comment]
added force-cache to the new list-possible-config-keys function

**Comment by perlpunk** [comment]
was merged. ad4eee6

**Pull request closed without merging**
